### ISSUE TITLE
boost::parser compilation error on mac with boost 1.88

### ISSUE THREAD

**Issue by SilkeSchomann** [boostorg/parser#269]
view_adaptor.hpp (boost::parser) does not compile on a mac with clang 18.1.8 and boost 1.88:

```
/include/boost/parser/detail/stl_interfaces/view_adaptor.hpp:199:35: error: no template named 'range_adaptor_closure' in namespace 'std::ranges'; did you mean 'std::__range_adaptor_closure'?
199 |     using range_adaptor_closure = std::ranges::range_adaptor_closure<D>;
    |                                                          ^~~~~~~~~~~~~
/bin/../include/c++/v1/__ranges/range_adaptor.h:58:8: note: 'std::__range_adaptor_closure' declared here
58 | struct __range_adaptor_closure {
   |            ^
1 error generated.
```

**Comment by jwwalker** [comment]
What version of the C++ standard are you using?  As far as I can tell with cppreference.com, range_adaptor_closure is a C++23 feature.

**Comment by SilkeSchomann** [comment]
We are using C++ 20 at the moment.

**Comment by jwwalker** [comment]
The line where you got a compile error is subject to `#if BOOST_PARSER_USE_CPP23_STD_RANGE_ADAPTOR_CLOSURE`.  Earlier in the same file, that macro is defined as follows:

```
#if BOOST_PARSER_USE_CONCEPTS && defined(__cpp_lib_ranges) &&                  \
    202202L <= __cpp_lib_ranges
#define BOOST_PARSER_USE_CPP23_STD_RANGE_ADAPTOR_CLOSURE 1
#else
#define BOOST_PARSER_USE_CPP23_STD_RANGE_ADAPTOR_CLOSURE 0
#endif
```

What is the value of `__cpp_lib_ranges` for you?  I take it you are not using Xcode and Apple Clang.  Maybe there is some mismatch between the compiler dialect and the version of the standard library you are using.

**Comment by progheal** [comment]
> Your stdlib is lying to you.

As this comment pointed out, the problem is not the version of *clang*, rather the version of *libc++*. IIRC Clang does not come with a pre-coupled libc++ version, one almost always *separately* install a version of libc++.

I found this issue when I encountered this exact problem when compiling from boost 1.89. I then checked my libc++ version using [this method](https://stackoverflow.com/a/38445708), which returns something like `#define _LIBCPP_VERSION 180000`, presumably some version 18. I then checked my package manager and found there is an upgrade to libc++ (according to it, it is "version 27c" upgrading to "version 29"), upgraded it, and the problem went away. The same version check now returns `#define _LIBCPP_VERSION 210000`, presumably some version 21.

TL;DR: try upgrade **libc++**.
